services:
  tic.ui:
    build:
      context: .
      dockerfile: TicTacToe.UI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgresConnectionString=Host=postgres;Database=TicTacToe;Username=postgres;Password=root
      - ConnectionStrings__Mongo=mongodb://mongo:27017
      - RabbitMQ__Host=rabbitmq
      - Jwt__Key=super_secret_key_12345_1313123123123123123211111111111111111111111111111111111111111111111111111111111111111
      - Jwt__Issuer=TicTacToeApp
    depends_on:
        - postgres
        - mongo
        - rabbitmq
    ports:
        - "7000:8080"
    networks:
        - rps-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: TicTacToe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rps-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - rps-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rps-network

networks:
  rps-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
